---
title: "April 2025 Employment Forecast"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---



#Setting up the various packages we might use to make our forecast. 
```{r}
library(tidyverse)
library(fpp3)
library(dplyr)
library(readxl)
library(tidyr)
library(tsibble)
library(tsibbledata)
library(lubridate)
library(feasts)
library(fable)
library(knitr)
library(ggstream)
library(ggpubr)
library(reshape2)
library(report)
library(readr)
urlfile="https://raw.githubusercontent.com/flynnecon/forecasting2025/refs/heads/main/data_files/nfp-assignment.csv"
```
#Getting the data read into R and then made into our time series analysis format. Note we do not need a training or test data division with the fact we are looking at a forecast 1 period ahead.
```{r Employment data work}
empdata202503 <- read_csv(url(urlfile))
empdata202503 <- empdata202503[c(2)]
empdata202503$date <- seq(as.Date("2001-01-01"), as.Date("2025-03-01"), by="1 month")
emp_tsbl202503 <- empdata202503 |> mutate(month=yearmonth(date)) |> as_tsibble(index=month)
```
